Revert "Use font-subset zip bundle"
This reverts commit 1743bf659da4f4b7fab7ef800ed806c23d0e3e18.

Reason for revert:

CommandException: No URLs matched: out/host_release/zip_bundles/font-subset.zip
WARNING:root:Command /b/s/w/ir/cache/vpython/a6c4d8/bin/python -u /b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py -- cp out/host_release/zip_bundles/font-subset.zip gs://flutter_infra_release/linux-x64/font-subset.zip failed with retcode 1, try 2.2.
WARNING:root:Trying harder: deleting tracker files
WARNING:root:Deleting tracker files failed: [Errno 2] No such file or directory: '/home/swarming/.gsutil'
ERROR:root:Command /b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py -- cp out/host_release/zip_bundles/font-subset.zip gs://flutter_infra_release/linux-x64/font-subset.zip failed 4 retries, giving up.

Original change's description:
> Use font-subset zip bundle
>
> Bug: https://github.com/flutter/flutter/issues/85080
> Change-Id: Id8081d87c8bcd0ae0ac1a41c7ce29cd796914cfb
> Reviewed-on: https://flutter-review.googlesource.com/c/recipes/+/14900
> Reviewed-by: Zach Anderson <zra@google.com>
> Commit-Queue: Dan Field <dnfield@google.com>

TBR=zra@google.com,godofredoc@google.com,flutter-scoped@luci-project-accounts.iam.gserviceaccount.com,fujino@google.com,dnfield@google.com

Change-Id: I4138d76095b6d5cb66a838f2e43885dd0ca4718d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: https://github.com/flutter/flutter/issues/85080
Reviewed-on: https://flutter-review.googlesource.com/c/recipes/+/14940
Reviewed-by: Zach Anderson <zra@google.com>
Commit-Queue: Zach Anderson <zra@google.com>