Revert "Update flutter_drone to process logs consistently."
This reverts commit fda21e40089b15a8cd6aff759ce8786fb37bdb2f.

Reason for revert: Many failures in CI of the form:

00:10 +62 -1: test/perf_tests_test.dart: runs perf tests, no crash if refresh rate percentage keys are not in the data [E]
  PathNotFoundException: Cannot open file, path = '/Volumes/Work/s/w/ir/x/w/recipe_cleanup/flutter_logs_dir/fake_result.json' (OS Error: No such file or directory, errno = 2)
  dart:io                                                  _File.readAsStringSync
  package:flutter_devicelab/tasks/perf_tests.dart 1403:77  PerfTest.internalRun.<fn>
  ===== asynchronous gap ===========================
  package:flutter_devicelab/framework/utils.dart 659:12    inDirectory
  ===== asynchronous gap ===========================
  test/perf_tests_test.dart 71:31                          main.<fn>

Original change's description:
> Update flutter_drone to process logs consistently.
>
> recipe_modules/logs_util provide the interface to process logs
> consitently across all the recipes but flutter_drone is not using it
> yet.
>
> Bug: https://github.com/flutter/flutter/issues/145791
> Change-Id: I495b482016b51338d5a8e2c01a981c3788b447d7
> Reviewed-on: https://flutter-review.googlesource.com/c/recipes/+/56800
> Reviewed-by: Ricardo Amador <ricardoamador@google.com>
> Commit-Queue: Godofredo Contreras <godofredoc@google.com>

TBR=godofredoc@google.com,keyonghan@google.com,flutter-scoped@luci-project-accounts.iam.gserviceaccount.com,ricardoamador@google.com

Change-Id: I792802528132aa2d2614fc144fc580d4caf44c95
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: https://github.com/flutter/flutter/issues/145791
Reviewed-on: https://flutter-review.googlesource.com/c/recipes/+/56784
Reviewed-by: Zach Anderson <zra@google.com>
Reviewed-by: Keyong Han <keyonghan@google.com>
Commit-Queue: Keyong Han <keyonghan@google.com>